# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :archive do |options|
    # add actions here: https://docs.fastlane.tools/actions
    cocoapods(
      use_bundle_exec: false
    )
    build_app(
      scheme: "JenkinsDemo", 
      configuration:options[:env], 
      "export_method": "development",
      silent: true,
      output_name: options[:name],
      output_directory: options[:path],
    )
  end
end
